server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/axon_db?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: axon_user
    password: axon_password
  data:
    redis:
      host: localhost
      port: 6379
      # password: (none)
      lettuce:
        pool:
          enabled: true
          max-active: 20
  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    com.axon: DEBUG

jwt:
  secret: "YOUR_VERY_SECRET_RANDOM_STRING_THAT_IS_LONG_ENOUGH_axonskusw"
