apiVersion: apps/v1
kind: Deployment
metadata:
  name: entry-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: entry-service
  template:
    metadata:
      labels:
        app: entry-service
    spec:
      containers:
        - name: entry-service
          image: nileyang/axon-entry:v1 # GitHub Actions가 교체할 부분
          ports:
            - containerPort: 8081
          resources:
            requests:
              memory: "1Gi"
              cpu: "300m"
            limits:
              memory: "2Gi"
              cpu: "800m"
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: axon-secrets
                  key: jwt-secret
            - name: PAYMENT_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: axon-secrets
                  key: payment-token-secret
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: axon-secrets
                  key: redis-password
            - name: SPRING_DATA_REDIS_HOST
              value: axon-redis-master
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: AXON_CORE_SERVICE_BASE_URL
              value: http://core-service:8080
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
              readOnly: true
          args: ["--spring.config.location=file:/app/config/application.yml,classpath:/application.yml"]
      volumes:
        - name: config-volume
          configMap:
            name: entry-config
---
apiVersion: v1
kind: Service
metadata:
  name: entry-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8081
  selector:
    app: entry-service
